### ISSUE TITLE
Use local composer

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii-dev#12]
Instead of using a `composer` binary that is assumed to be in the path I propose downloading our own binary and running it with a different configuration directory.

This will allow us, for example, to enable: https://github.com/hirak/prestissimo for faster installation.

**Comment by samdark** [comment]
Are there developers without composer installed?

**Comment by SamMousa** [comment]
No, but there are probably developers that don't want things like the global package i mentioned above.

So we could do global composer but with different environment as well and get the same advantages :)

**Comment by samdark** [comment]
If developer doesn't want to use hirak/prestissimo for some reason, I guess he do not want to use it with this tool as well.

**Comment by SamMousa** [comment]
The only reason is packages not being compatible; I'd just say that we could offer a standard ENV file that has it enabled, and the local dev can override it.

The goal is to make it as easy as possible by default, without removing power from the developer right?
We could do: `composer.env.dist` and `composer.env` and use them before executing composer.

It's just an idea; I always use the above plugin, but even with that installation is slow, I can imagine not having it will make installation take ages...

**Comment by samdark** [comment]
Would having hirak/prestissimo mentioned in readme be enough?

**Comment by SamMousa** [comment]
That's fine for me, since people will have to read docs anyway to get started on this Yii3 development.
