### ISSUE TITLE
No Way Easy Way To Setup Initial Forks 

### ISSUE THREAD

**Issue by BillHeaton** [yiisoft/yii-dev#18]
Apparently there is no easy way to set up the initial forks on the packages listed packages.php

`./yii-dev setup`

would be most helpful.  Any suggestions for interim would be gratefully accepted.

**Comment by samdark** [comment]
Do you mean automating the following?

> In order to use your own fork copy `packages.php` to `packages.local.php` and replace `yiisoft` with your github username.

**Comment by BillHeaton** [comment]
Not really.  

If I run "./yii-dev install"  It gives an error for each package of "_no composer.json in yiisoft/xxx, skipping composer install._"  If obviously wants me to clone and/or fork each of the packages before hand. 

For ~80 packages that's a lot of work to get the boat in the water.

I envision "./yii-dev setup" would do the initial clone of each package in the proper place. (or perhaps somehow get the correct composer.json into the right project directory.  It could ignore projects that already have a composer.json fill in the project directory.

Another option would be just the minimum to things going and then perhaps an "./yii-dev add" to proceed past that point.

**Comment by samdark** [comment]
Yes, forking is necessary and I'm not sure it can be automated. Cloning is automated already.

**Comment by BillHeaton** [comment]
Pointer for cloning automating?

**Comment by BillHeaton** [comment]
Got it... Clone errors are not being acted upon.  This causes composerInstall() to fail because of the missing _composer.json_ file.

Once I switched to  `install --http`,  it started working.  

I suggest we change the title on this one or merge with #11.   I'm going to start looking #11 as it would have made thing a lot clearer.

**Comment by samdark** [comment]
@BillHeaton #11 seems to be solved now.

**Comment by rugabarbo** [comment]
@samdark I have added explicit notifications of any cloning issues to finally resolve this issue. I tested the implementation. 

Notification example:
```
Some packages have issues...

Package yiisoft/access error:

Cloning into '/yii-dev/commands/../dev/access'...
ssh: connect to host gitub.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by BillHeaton** [comment]
Suggestion "or use option "--http" 
This is what worked for me.

**Comment by BillHeaton** [comment]
I'm playing with a refactoring of yii-dev to get some experience with console commands.  It may never be useful however it's a nice simple app that'll give me the a good playpen. 

I'm making good progress and so far it  removes a lot of redundant code and improves argument processing.

I wanted to create a superclass definition for a portion of the code. The question that is stumping me is: "Where would I put the the code?"  

yii-dev/commands just seems wrong.  In Y2 I'd probably put it in app/models.

**Comment by samdark** [comment]
@BillHeaton but please be aware that master branch got @rugabarbo refactoring recently so if you haven't update, likely you're doing the same thing.

**Comment by BillHeaton** [comment]
Ack. Wll update. Thanks!
